# Generated by Django 3.1.1 on 2020-09-07 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_auto_20200907_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='title',
            field=models.SlugField(max_length=35, unique=True, verbose_name='Название'),
        ),
    ]
