# Generated by Django 3.1.1 on 2020-09-08 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_auto_20200907_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='color',
            field=models.CharField(blank=True, max_length=35, null=True, verbose_name='Цвет'),
        ),
        migrations.AddField(
            model_name='tag',
            name='text',
            field=models.CharField(blank=True, max_length=35, null=True, verbose_name='Отображаемое название'),
        ),
    ]
