# Generated by Django 3.1.1 on 2020-09-10 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0012_shoppinglist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppinglist',
            name='recipes',
            field=models.ManyToManyField(blank=True, null=True, related_name='recipe_to_buy', to='recipes.Recipe'),
        ),
    ]
